GET http://localhost:8080/book
Accept: application/json

###
POST http://localhost:8080/book
Content-Type: application/json

{
    "id": 5,
    "title": "Hacking with Spring Boot 2.3: Reactive Edition",
    "author": "Greg L. Turnquist",
    "publisher": "Amazon.com Services LLC",
    "releaseDate": "May 2020",
    "isbn": "B086722L4L",
    "topic": "Spring"
 }

###
GET http://localhost:8080/book/5
Accept: application/json

###
PUT http://localhost:8080/book/2
Content-Type: application/json
Accept: application/json

{
  "title": "Hacking with Spring Boot 2.3: Reactive Edition",
  "author": "Alou",
  "publisher": "Amazon.com Services LLC",
  "releaseDate": "May 2020",
  "isbn": "B086722L4L",
  "topic": "Spring"
}

###
DELETE http://localhost:8080/book/3
Accept: application/json